[project]
name = "manigpt-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "manikamg", email = "36034033+manikamg@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.142.2",
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.15.1",
    "python-dotenv>=1.2.4",
    "sqlalchemy>=2.1.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
manigpt-api = "manigpt_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
